@startuml

Title App Get File

actor User
participant Wallet
participant Dapp
control Hub

User -> Dapp: Get File
Dapp -> Wallet: AccessFile(peerId, meta)
Wallet -> Wallet: CheckConnected()

Wallet -> Wallet: GetFileDescription(meta)
Wallet -> Wallet: GetPeerDescription(peerId)

Wallet -> User: notify(meta, peer)

note right of User: Approve access

User -> Wallet: Approve()
Wallet -> Wallet: GenerateAuthToken(peerId)
Wallet -> Dapp: token
Dapp -> Hub: GetFile(meta, token)


@enduml
