@startuml

Title Pod Registration

actor User
participant Wallet
participant Dapp
control Pod

User -> Dapp: Register Pod
Dapp -> Wallet: registerNode(peerId)
Wallet -> User: notify(origin)

note right of User: Warning. \nPod will access \nALL your files!

User -> Wallet: Approve()
Wallet -> Wallet: AddRegistration(peerId, origin)
Wallet -> Wallet: AddConnected(origin)
Wallet -> Dapp: pubKey
Dapp -> Pod: SetOwner(pubKey)
Pod -> Pod: AddOwner(pubKey)
Dapp <-- Pod: success
User <-- Dapp: success

@enduml
